apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: "3.3.7"
  interval: 1h0m0s
  releaseName: kyverno
  targetNamespace: kyverno-system
  values:
    admissionController:
      rbac:
        clusterRole:
          extraResources:
          - apiGroups:
            - ''
            resources:
            - secrets
            verbs:
            - create
            - update
            - delete
            - list
            - get
    backgroundController:
      rbac:
        clusterRole:
          extraResources:
          - apiGroups:
            - ''
            resources:
            - secrets
            verbs:
            - create
            - update
            - delete
            - patch
            - get
    cleanupController:
      rbac:
        clusterRole:
          extraResources:
          - apiGroups:
            - ''
            resources:
            - secrets
            verbs:
            - delete
            - list
            - watch
            - get
    reportsController:
      rbac:
        clusterRole:
          extraResources:
          - apiGroups:
            - ''
            resources:
            - secrets