---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: interfaces
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./platform/interfaces
  prune: true
  dependsOn:
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  retryInterval: 1m0s