apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qdrant
  namespace: flux-system
spec:
  chart:
    spec:
      chart: qdrant
      sourceRef:
        kind: HelmRepository
        name: qdrant
      version: "1.13.6"
  interval: 1h0m0s
  releaseName: qdrant
  targetNamespace: qdrant